### ISSUE TITLE
Nx roadmap

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#76]
* [x] Random generators
* [x] Unary ops
* [x] Element-wise binary ops
* [x] Element-wise comparison ops
* [x] Other operations provided by XLA as needed
* [x] FP16 types
* [ ] Complex types
* [ ] Handling of NaN and Infinity (?)
