### ISSUE TITLE
device roadmap

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#79]
* [x] Streamline and document device ordinal handling
* [x] Add an option to return supported platforms
* [x] Allocate data on multiple devices by a given dimension
* [x] Stream data into device
* [x] Stream data into multiple devices (for pmap)
* [x] Read data from multiple devices into a single binary (for pmap)
